### ISSUE TITLE
Can't find on mavenCentral()

### ISSUE THREAD

**Issue by vanniktech** [lavcraft/huntbugs-gradle-plugin#9]
```groovy
buildscript {
  repositories { jcenter() }

  dependencies {
    classpath 'one.util.huntbugs:huntbugs-gradle-plugin:x.x.+'
  }
}

apply plugin: 'one.util.huntbugs'
```

does not seem to work. Also when I [search](http://search.maven.org/#search%7Cga%7C1%7Cone.util.huntbugs) for it, I can't find it.

**Comment by lavcraft** [comment]
Oh, sorry. I have forgotten publish it to jcenter. I have sent publish request to jcenter. Wait

If you need to use plugin now, see [huntbugs at gradle plugins portal](https://plugins.gradle.org/plugin/one.util.huntbugs)

**Comment by lavcraft** [comment]
I have published to jcenter, example from above – works fine (just set valid version)

**Comment by vanniktech** [comment]
Alright thanks !

**Comment by lavcraft** [comment]
Thanks for the report too!
